# Generated by Django 3.2.13 on 2022-05-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_homecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homecategory',
            old_name='categoryImage',
            new_name='homeCategoryImage',
        ),
        migrations.AddField(
            model_name='category',
            name='CategoryImage',
            field=models.ImageField(blank=True, default='category/default.jpg', upload_to='category'),
        ),
    ]
