# Generated by Django 3.2.13 on 2022-05-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220509_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='homecategories',
            field=models.ManyToManyField(blank=True, to='products.HomeCategory'),
        ),
    ]
