# Generated by Django 3.2.13 on 2022-05-18 23:36

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_homecategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # ('image', models.ImageField(upload_to=products.models.image_upload_to_slide)),
            ],
        ),
    ]
